### ISSUE TITLE
Update build.bat to VS 2022

### ISSUE THREAD

**Issue by ClemensLinnhoff** [eclipse/openmcx#6]
### Problem:
The build.bat script to install OpenMCx on Windows does check for Visual Studio 2022. Also, an old version of vcpkg is checked out from the script.

### Solution:
- add `17 2022` [here](https://github.com/eclipse/openmcx/blob/main/build.bat#L28)
- change vcpkg release checkout to `2022.10.19` [here](https://github.com/eclipse/openmcx/blob/main/build.bat#L13)

I would have created a pull request, but I do not have authorization to create a new branch.

**Comment by klausschuch** [comment]
Updated the build script-

@ClemensLinnhoff If you want to create a pull request, please fork the repository, create a branch in your fork and then create a pull request for your branch to the main repository.
